/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    servicii: Servicii;
    proiecte: Proiecte;
    blog: Blog;
    integrari: Integrari;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    servicii: ServiciiSelect<false> | ServiciiSelect<true>;
    proiecte: ProiecteSelect<false> | ProiecteSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    integrari: IntegrariSelect<false> | IntegrariSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicii".
 */
export interface Servicii {
  id: number;
  titlu: string;
  slug: string;
  /**
   * Mai mic = mai sus în listă
   */
  ordine?: number | null;
  metaTitlu?: string | null;
  imagine: number | Media;
  descriereMeniu?: string | null;
  descriereScurta?: string | null;
  heroTitlu?: string | null;
  heroSubtitlu?: string | null;
  heroCuvantInel?: string | null;
  continut?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  pret?: string | null;
  tipuri?:
    | {
        titlu: string;
        subtitlu?: string | null;
        descriere?: string | null;
        logouri?: string | null;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        icon?: string | null;
        titlu: string;
        descriere?: string | null;
        id?: string | null;
      }[]
    | null;
  integrari?:
    | {
        eticheta: string;
        elemente: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lista structurată folosită pe site. Câmpul text vechi rămâne temporar ca fallback.
   */
  integrariCatalog?: (number | Integrari)[] | null;
  preturi?:
    | {
        nume: string;
        pret?: string | null;
        include?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        intrebare: string;
        raspuns: string;
        id?: string | null;
      }[]
    | null;
  deliverables?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrari".
 */
export interface Integrari {
  id: number;
  nume: string;
  slug: string;
  aliasuri?:
    | {
        valoare: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Cale din public, de exemplu /integrari/maib.svg
   */
  logoFisier?: string | null;
  /**
   * Bifează pentru logo-uri albe care au nevoie de fundal închis
   */
  logoFundalInchis?: boolean | null;
  logoAlt?: string | null;
  categorie:
    | 'plati-online'
    | 'rate-finantare'
    | 'curierat-fulfillment'
    | 'erp-stoc-contabilitate'
    | 'crm-vanzari'
    | 'marketplace-feeduri'
    | 'marketing-analytics'
    | 'automatizari-comunicare'
    | 'programari-sisteme-custom';
  regiuni: ('md' | 'ro' | 'ue' | 'international')[];
  rezumat: string;
  capabilitati?:
    | {
        valoare: string;
        id?: string | null;
      }[]
    | null;
  cerinte?:
    | {
        valoare: string;
        id?: string | null;
      }[]
    | null;
  durata?: string | null;
  pret?: string | null;
  featuredHome?: boolean | null;
  ordine?: number | null;
  paginaPublica?: boolean | null;
  continut?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faq?:
    | {
        intrebare: string;
        raspuns: string;
        id?: string | null;
      }[]
    | null;
  urlOficial?: string | null;
  seo?: {
    metaTitlu?: string | null;
    metaDescriere?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proiecte".
 */
export interface Proiecte {
  id: number;
  titlu: string;
  slug: string;
  imagine: number | Media;
  linkLive?: string | null;
  /**
   * Ex: Next.js, Netopia, FAN Courier, SmartBill
   */
  tehnologii?: string | null;
  /**
   * Selectează numai integrările verificate în proiect.
   */
  integrariConfirmate?: (number | Integrari)[] | null;
  studiuDeCaz?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Primul serviciu selectat este eticheta principală a proiectului.
   */
  servicii: (number | Servicii)[];
  seo?: {
    titluSEO?: string | null;
    descriereSEO?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  titlu: string;
  slug?: string | null;
  categorie: 'magazin-online' | 'seo' | 'web-design' | 'integrari' | 'ai-automatizari' | 'sfaturi';
  excerpt: string;
  autor?: string | null;
  publicatLa?: string | null;
  coverImage: number | Media;
  continut: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  integrariMentionate?: (number | Integrari)[] | null;
  seo?: {
    titluSEO?: string | null;
    descriereSEO?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'servicii';
        value: number | Servicii;
      } | null)
    | ({
        relationTo: 'proiecte';
        value: number | Proiecte;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'integrari';
        value: number | Integrari;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicii_select".
 */
export interface ServiciiSelect<T extends boolean = true> {
  titlu?: T;
  slug?: T;
  ordine?: T;
  metaTitlu?: T;
  imagine?: T;
  descriereMeniu?: T;
  descriereScurta?: T;
  heroTitlu?: T;
  heroSubtitlu?: T;
  heroCuvantInel?: T;
  continut?: T;
  pret?: T;
  tipuri?:
    | T
    | {
        titlu?: T;
        subtitlu?: T;
        descriere?: T;
        logouri?: T;
        id?: T;
      };
  features?:
    | T
    | {
        icon?: T;
        titlu?: T;
        descriere?: T;
        id?: T;
      };
  integrari?:
    | T
    | {
        eticheta?: T;
        elemente?: T;
        id?: T;
      };
  integrariCatalog?: T;
  preturi?:
    | T
    | {
        nume?: T;
        pret?: T;
        include?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        intrebare?: T;
        raspuns?: T;
        id?: T;
      };
  deliverables?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proiecte_select".
 */
export interface ProiecteSelect<T extends boolean = true> {
  titlu?: T;
  slug?: T;
  imagine?: T;
  linkLive?: T;
  tehnologii?: T;
  integrariConfirmate?: T;
  studiuDeCaz?: T;
  servicii?: T;
  seo?:
    | T
    | {
        titluSEO?: T;
        descriereSEO?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  titlu?: T;
  slug?: T;
  categorie?: T;
  excerpt?: T;
  autor?: T;
  publicatLa?: T;
  coverImage?: T;
  continut?: T;
  integrariMentionate?: T;
  seo?:
    | T
    | {
        titluSEO?: T;
        descriereSEO?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrari_select".
 */
export interface IntegrariSelect<T extends boolean = true> {
  nume?: T;
  slug?: T;
  aliasuri?:
    | T
    | {
        valoare?: T;
        id?: T;
      };
  logoFisier?: T;
  logoFundalInchis?: T;
  logoAlt?: T;
  categorie?: T;
  regiuni?: T;
  rezumat?: T;
  capabilitati?:
    | T
    | {
        valoare?: T;
        id?: T;
      };
  cerinte?:
    | T
    | {
        valoare?: T;
        id?: T;
      };
  durata?: T;
  pret?: T;
  featuredHome?: T;
  ordine?: T;
  paginaPublica?: T;
  continut?: T;
  faq?:
    | T
    | {
        intrebare?: T;
        raspuns?: T;
        id?: T;
      };
  urlOficial?: T;
  seo?:
    | T
    | {
        metaTitlu?: T;
        metaDescriere?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}